# $Id$

send_user "In $tool.0/test.exp.\n"

proc parse_output {output} {

  set found_test 0
  set lines [split $output \n]

  foreach line $lines {
    if [regexp -nocase "test: " $line] {
       set found_test 1
       if [regexp -nocase "test:  *expect.* *fail" $line] {
	   setup_xfail "*"
       } elseif [regexp -nocase "test:  *pass" $line] {
	   pass "$line"
	   clear_xfail "*"
       } else {
           fail "$line"
	   clear_xfail "*"
       }
    }
  }
  return $found_test
}

proc run_test {} {

  global tool
  global ${tool}_start
  global comp_output
  global comp_completion_code

  if {!$comp_completion_code} {
     fail $comp_output
  } elseif [info exists comp_output] {
     if ![parse_output $comp_output] {
        fail "Test not found."
     }
  } else {
     fail "No output from $tool."
  }
  	
}

run_test
