#!/bin/sh
#
# export
# Geoffrey Furnish
# 24 September 1997
#
# @> This script is based on GTS's gtsexp.
###############################################################################

pwd=`pwd`
proj=`basename $pwd`

if [ -f .import ]; then
	# export files newer than .import.
	echo "Exporting files modified since last import."

	check_new="-newer $proj/.import"

else
	# Need to export all files.
	echo "Exporting entire file tree."

	check_new=" "
fi

# Now we need to figure out which environments are in use.

envlist=`find . -name .env_\* | sed 's/.*.env_//g' | sort | uniq`

# Now cycle through each environment, and add to the exclusion list.

x=""
for v in $envlist; do
    x=$x" ! -name $v"
    x=$x" ! -path \*/$v/\*"
    x=$x" ! -name \*_$v"
    x=$x" ! -name lib\*_$v\*"
    x=$x" ! -path \*/${v}_repository\*"
done

#echo "envlist=$envlist"
#echo "x=$x"

# An oddity to consider.  Do we want to let Emacs autosave files propagate?
# ! -path \*/#\*#

cd ..

# We have to use eval here, or $x isn't correctly considered.

eval find $proj \
	$check_new \
	$x \
	! -path \*CVS/\* ! -name .cvsignore ! -name \*~ \
	! -path \*/.\*depend ! -name .d.\* ! -name .env_\* \
	! -name .nml_\* ! -name .pt\* ! -name .dkcc.\* \
	! -name .nmlgen ! -name .prstgen \
	! -path \*config/.pooma.\* \
	! -path \*/ii_files/\* ! -path \*/KCC_files/\* \
	! -name \*_prs.cc ! -name \*.flc \
	! -path \*__pt__\*.c \
	! -name \*.dat ! -name \*.log ! -name run.log.\* ! -name \*.out \
	! -name core ! -name mppcore ! -name \*.pure \
	-type f -print > $proj.exportlist

tar --files-from=$proj.exportlist  -cvf $proj.tar

/bin/rm $proj.exportlist

# This is how it used to be.
#tar cvf gts.tar \
#	`find gts \
#	$check_new $follow \
#	$x \
#	-type f`

gzip $proj.tar

echo "The resulting file is:"
ls -l $proj.tar.gz
echo "You may now download $proj.tar.gz to the remote site."

exit



	! -path \*__pt__\*.c \
	! -path \*.dat ! -path \*.log ! -name run.log.\* ! -path \*.out \
	! -path \*/nml_\*.h ! -path \*/nml_\*.cc \
	! -name gweight.h ! -name gweight_\*.cc \
	! -name nmtest \
	! -name tgf ! -name tgts ! -name tgstream \
	! -name ndxfile ! -name tlog ! -name geom ! -name geom2 \
	! -name mt1 ! -name mode_list ! -name prst ! -name integrate \
	! -name mat ! -name fft ! -name tGQ ! -name phisolv \
	! -name \*.ii \
	! -path \*/ptest/t1 \
	! -path gts/src/ds++/x\* \
	! -name tArraySwap ! -name tSyncAll \
	! -name tgsync ! -name tBSwap \
	! -path \*.3 \
	! -name gts.ps ! -name gts.dvi ! -name gts.info \
	! -path \*.aux ! -path \*.toc ! -path \*.cp \
	! -name libgts.tex ! -name libds++.tex \
	! -path \*/src/run\* ! -path \*/src/e\* \
	! -name FILES \





	! -path \*repository\* \
	! -path \*/ii_files/\* \
	! -path \*/.\*depend ! -path \*/.d.\* \
	! -path \*~ ! -path \*.o ! -path \*.a ! -path \*.sl \
	! -path \*.so.\* ! -path \*_elf.so\* ! -path \*_mpi.so\* \
	! -path \*__pt__\*.c \
	! -path \*.dat ! -path \*.log ! -name run.log.\* ! -path \*.out \
	! -path \*_prs.cc ! -path \*.flc \
	! -path \*/nml_\*.h ! -path \*/nml_\*.cc \
	! -name gweight.h ! -name gweight_\*.cc \
	! -path gts/src/gts/gts \
	! -path gts/src/gtsinit/gtsi \
	! -path \*_wish \
	! -name nmtest ! -name core ! -name mppcore \
	! -name tgf ! -name tgts ! -name tgstream \
	! -name ndxfile ! -name tlog ! -name geom ! -name geom2 \
	! -name mt1 ! -name mode_list ! -name prst ! -name integrate \
	! -name mat ! -name fft ! -name tGQ ! -name phisolv \
	! -name pgts ! -name pgtsi \
	! -name \*_hp ! -name \*_pgn ! -name \*_pgi \
	! -name \*_mpi ! -name \*_mpid \
	! -name \*_mpio ! -name \*_mpio2 ! -name \*_mpio3 \
	! -name \*_tgcc ! -name \*_gcc ! -name \*_elf \
	! -name \*_sgi \
	! -name \*.ii \
	! -path \*/ptest/t1 \
	! -path gts/src/ds++/x\* \
	! -name tArraySwap ! -name tSyncAll \
	! -name tgsync ! -name tBSwap \
	! -path \*.3 \
	! -name gts.ps ! -name gts.dvi ! -name gts.info \
	! -path \*.aux ! -path \*.toc ! -path \*.cp \
	! -name libgts.tex ! -name libds++.tex \
	! -path \*/src/run\* ! -path \*/src/e\* \
	! -name FILES \

