puts "Running test of C4 tReduce component."

global ENV
global C4
global Serial

puts "ENV = $ENV"
puts "C4 = $C4"

load_lib draco.exp

if {$Serial} { set maxprocs 1 } else { set maxprocs 8 }

for {set np 1} {$np <= $maxprocs} {incr np} {
    puts "test.exp: np=$np"
    puts "Running tReduce_$ENV on $np nodes."

    set x "tReduce_$ENV -np $np"

    set err [catch {set output [c4run $np tReduce_$ENV]}]
#    puts "err=$err output=$output"

    set lines [split $output \n]

    foreach line $lines {
#	puts "analyzing line: $line"
	if {[regexp "correct" $line]} {
	    pass "$x : $line"
	} else {
	    fail "$x : $line"
	}
    }
}

# All done with tests of tReduce_$(env)
