extraheaders := cmath ctime cctype cstdlib cstring cassert cfloat

extraInstallHeaders := $(addprefix ${includedir}/${package}/, ${extraheaders})

install: ${extraInstallHeaders}

uninstall: extraUninstall

.PHONY: extraUninstall

extraUninstall:
	-${UNINSTALL} ${extraInstallHeaders}

