###############################################################################
# parser/test Makefile.target
# Thomas M. Evans
# Wed Nov  7 15:54:59 2001
# $Id$
###############################################################################
# @> General Makefile.target for parser/test
###############################################################################

datasrc := ${srcdir}/parser_test.inp ${srcdir}/scanner_test.inp

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libparser_test${libsuffix}
thistestlib := -L. -lparser_test
thistestlib_dep := parser_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

all: tstConsole_Token_Stream

check: generate

generate: tstConsole_Token_Stream
	chmod 750 $(test_alltarget)


###############################################################################
#			 end of parser/test Makefile.target
###############################################################################
