puts "Running tests of DS++ Mat component."

load_lib draco.exp

global ENV

puts "value of ENV is $ENV"

puts "Running tstMat_$ENV"

set output [exec tstMat_$ENV]

# Check the output of t1

if {[regexp "t1: passed" $output]} {
    pass t1
} else {
    fail t1
}

# Check the output of t2

if {[regexp "t2a: passed" $output]} {
    pass t2a
} else {
    fail t2a
}

if {[regexp "t2b: passed" $output]} {
    pass t2b
} else {
    fail t2b
}

if {[regexp "t2c: passed" $output]} {
    pass t2c
} else {
    fail t2c
}

# All done with tests of tstMat_$(env)
