###############################################################################
# draco/src/mc/test Makefile.target
# Thomas M. Evans
# Fri Apr 16 15:45:08 1999
# $Id$
###############################################################################
# @> General Makefile.target for draco/src/mc/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libMC_Test${libsuffix}
thistestlib := -L. -lMC_Test
thistestlib_dep := MC_Test.o DD_Mesh.o

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${LD} ${LDFLAGS} -o $@ ${thistestlib_dep} ${testlibs}

objs += ${thistestdep}

###############################################################################
#			 end of draco/src/mc/test Makefile.target
###############################################################################
