###############################################################################
# draco/src/mc/test Makefile.target
# Thomas M. Evans
# Fri Apr 16 15:45:08 1999
# $Id$
###############################################################################
# @> General Makefile.target for draco/src/mc/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

${test_alltarget}: ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

###############################################################################
#			 end of draco/src/mc/test Makefile.target
###############################################################################
