###############################################################################
# draco/src/viz/test Makefile.target
# Thomas M. Evans
# Mon Jan 31 15:44:31 2000
# $Id$
###############################################################################
# @> General Makefile.target for draco/src/viz/test
###############################################################################

##---------------------------------------------------------------------------##
## SOURCE FILES
##---------------------------------------------------------------------------##

##---------------------------------------------------------------------------##
## python files

pysrc := $(wildcard ${srcdir}/python/*.py)
pyobj := $(notdir ${pysrc})

##---------------------------------------------------------------------------##
## benchmark files

datasrc := $(wildcard ${srcdir}/bench/*.0001)
dataobj := $(notdir ${datasrc})

casesrc := $(wildcard ${srcdir}/bench/*.case)
caseobj := $(notdir ${casesrc})

objs := ${pyobj} ${dataobj} ${caseobj}

##---------------------------------------------------------------------------##
## dependencies
##---------------------------------------------------------------------------##

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

##---------------------------------------------------------------------------##
## RULES
##---------------------------------------------------------------------------##

${test_alltarget}: ${testdeps} ${objs}

tstEnsight_Translator: tstEnsight_Translator.o
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

%.py: python/%.py
	cp $< .

%: bench/%
	cp $< .

test_output_files += tstEnsight_Translator.o tstEnsight_Diff  *.pyc *.diff

dirstoclean += testproblem_ensight

###############################################################################
#			 end of draco/src/viz/test Makefile.target
###############################################################################
