puts "Running test of C4 tBSwap component."

global ENV
global C4
global Serial

puts "ENV = $ENV"
puts "C4 = $C4"

load_lib draco.exp

if {$Serial} { set maxprocs 1 } else { set maxprocs 8 }

proc runit {np args} {
#    set output [c4run $np $args]
    if [catch {c4run $np $args} output] {
       error "Execution failed! output=\"$output\""
    }
#    puts "output is :$output:"

    set lines [split $output \n]

    foreach line $lines {
	if {[regexp "Test " $line]} {
	    if {[regexp "Test passed" $line]} {
		return 1
	    } else {
		return 0
	    }
	}
    }

    puts "Going to signal an error."
    error "Execution failed!"
}

for {set np 1} {$np <= $maxprocs} {incr np} {
    puts "test.exp: np=$np"
    puts "Running tBSwap_$ENV on $np nodes."

    set x "tBSwap_$ENV -np $np"

    set err [catch {runit $np tBSwap_$ENV} rc]
#    puts "err=$err rc=$rc"

    if {$err} {
	fail "$x : rc=\"$rc\""
    } elseif { $rc } {
	pass $x
    } else {
	fail $x
    }
}

# All done with tests of tBSwap_$(env)
