#!python
# Geoffrey Furnish
# 15 January 1998
#-----------------------------------------------------------------------------#

import sys, posix
DRACO_ROOT = posix.environ ['DRACO_ROOT']
sys.path.append(DRACO_ROOT+"/pylib")
sys.path.append(DRACO_ROOT+"/pydraco")
#sys.path.append(HED_ROOT+"/src/geom")
#sys.path.append(HED_ROOT+"/src/hydro")

from ADFX import *

adfx = ADFX()
adfx.mainloop()
