# override the source and object definitions for the package

csrc = $(wildcard ${srcdir}/*.c)
ccsrc = Mesh_DB.cc Mesh_XYZ.cc Release.cc
cobjs = $(notdir $(patsubst %.c,%.o,${csrc}))
ccobjs = $(notdir $(patsubst %.cc,%.o,${ccsrc}))
objs = ${cobjs} ${ccobjs}
