###############################################################################
# meshReaders_Services/test Makefile.target
# Thomas M. Evans
# Wed Mar 27 14:53:05 2002
# $Id$
###############################################################################
# @> General Makefile.target for meshReaders_Services/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libmeshReaders_Services_test${libsuffix}
thistestlib := -L. -lmeshReaders_Services_test
thistestlib_dep := meshReaders_Services_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of meshReaders_Services/test Makefile.target
###############################################################################
