###############################################################################
# draco/src/ds++/test Makefile.target
# Randy M. Roberts
# Time-stamp: <99/02/10 16:43:44 mcghee>
###############################################################################
# @> Target makefile for DS++ component tests
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

${test_alltarget}: ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

###############################################################################
#			 end of draco/src/ds++/test Makefile.target
###############################################################################
