###############################################################################
# ds++/test Makefile.target
# Thomas M. Evans
# Wed Nov  7 15:54:59 2001
# $Id$
###############################################################################
# @> General Makefile.target for ds++/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libds_test${libsuffix}
thistestlib := -L. -lds_test
thistestlib_dep := ds_test.o 
thistest_lintmodules := $(wildcard ${srcdir}/*.lnt)

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

flint:
	@if test -n ${FLEXELINT}; then \
	  for lintmodule in ${thistest_lintmodules}; do \
	    pushd ${srcdir}; \
	    ${FLEXELINT} $${lintmodule}; \
            popd; \
	  done; \
	else \
	  echo "I don't know where flexelint is located."; \
	  exit 1; \
	fi;\
	exit 0;

###############################################################################
#			 end of ds++/test Makefile.target
###############################################################################
