.TH "<CLASS>" 1 "<DATE>" "libds++.a"

.SH NAME
<SHORT_SNIP>

.SH DESCRIPTION
<CLASS_DESCRIPTION>

.SH DECLARATION
<CLASS_DECL>

.SH METHODS
<CLASS_METHODS>

.SH USAGE
.in .5i
All C++ classes in the GTS programming environment are made available
by including the header file which defines them.  For most GTS
classes, this is accomplished by using the directory qualified
pathname.  However, for the classes in the C++ Data Structures
library, the GTS makefiles issue a a suitable "-I" directive so that
only the base name is required.  For this class, the correct directive
is: 

.in 2i
#include "<FILE>"
.in .5i

Note that for Cfront based C++ compilers, it is necessary to give the
same "-I" directives at link time, as were used during compilation.

Finally, in order to link, you have to specify appropriate -L and -l
options to specify the location and name of the desired libraries.
For this class it would look something like this:

.nf
.in 1i
CC -I.. -I../ds++ -c foo.cc
CC -I.. -I../ds++ -o foo foo.o -L../ds++ -lds++
.in .5i
.fi

This assumes you are currently in a subdirectory of the GTS toplevel
source directory (a sibling directory of base, ds++, etc.).  You will
need to change the ".." in the above to be some more fully specified
path if you are compiling from some other area of the filesystem.

.SH REVISION HISTORY
The revision history for the file declaring <CLASS> is:
.in 1i
<DECL_REVISION>
.in .5i

The revision history for the file implementing <CLASS> is:
.in 1i
<IMPL_REVISION>
.in .5i
