###############################################################################
## tstPlot2D_Diff.py
## Rob Lowrie
## $Id$
###############################################################################

import string

##---------------------------------------------------------------------------##
## tstPlot2D_Diff.py
#
#  Checks standard tstPlot2D output.
##---------------------------------------------------------------------------##

def diffFiles(fileName1, fileName2, ignore):
  '''
  Compares two files, ignoring lines with the strings
  defined in the list ignore.  Returns 1 if the files differ,
  0 otherwise.
  '''
  f1 = open(fileName1, 'r')
  f2 = open(fileName2, 'r')
  while 1:
      line1 = f1.readline()
      line2 = f2.readline()
      if len(line1) == 0:
          # then EOF for first file
          if len(line2) != 0:
              print fileName1,'and',fileName2,'are of different length!'
              return 1
          else:
              return 0
      if len(line2) == 0:
          print fileName1,'and',fileName2,'are of different length!'
          return 1
      check = 1
      for s in ignore:
          if string.find(line1, s) != -1:
              check = 0
              break
      if check and line1 != line2:
          print fileName1,'and',fileName2,' differ here:'
          print line1, line2
          return 1
  return 0 # should not get here

# Files generated by test code
files = ['plot1.agr',
         'plot2.agr',
         'plot3.agr',
         'plot4.agr']

# Prefix to add to compare files to
benchPrefix = 'bench_'

# ignore lines that contain these strings
ignoreLines = ['@version',
               '@timestamp']

for f in files:
    benchFile = benchPrefix + f
    if diffFiles(f, benchFile, ignoreLines):
        print 'tstPlot2D_Diff Test: FAILED on file %s' % f


###############################################################################
##                            end of tstPlot2D_Diff.py
###############################################################################

