###############################################################################
# draco/src/imc/test Makefile.target
# Thomas M. Evans
# Tue Apr 27 12:03:47 1999
# $Id$
###############################################################################
# @> General Makefile.target for draco/src/imc/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep     := libIMC_Test${libsuffix}
thistestlib     := -L. -lIMC_Test
thistestlib_src := $(wildcard ${srcdir}/*_pt.cc)
thistestlib_dep := $(notdir $(patsubst %.cc, %.o, ${thistestlib_src}))\
                   IMC_Test.o IMC_DD_Test.o imc_test.o

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of draco/src/imc/test Makefile.target
###############################################################################
