###############################################################################
# draco/src/imc/test Makefile.target
# Thomas M. Evans
# Tue Jan 12 10:41:02 1999
# Time-stamp: <99/02/02 15:26:16 rsqrd>
###############################################################################
# @> Target makefile for IMC component tests
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

${test_alltarget}: ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

###############################################################################
#			 end of draco/src/imc/test Makefile.target
###############################################################################
