###############################################################################
# draco/src/imc/test Makefile.target
# Thomas M. Evans
# Tue Apr 27 12:03:47 1999
# $Id$
###############################################################################
# @> General Makefile.target for draco/src/imc/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

${test_alltarget}: ${testdeps}

tstOpacity_dep = tstOpacity.o tstOpacity_pt.o
tstTally_dep = tstTally.o tstTally_pt.o
tstParticle_dep = tstParticle.o tstParticle_pt.o tstTally_pt.o
tstTopology_Builder_dep = tstTopology_Builder.o \
                          tstTopology_Builder_pt.o 
tstSource_Builder_dep = tstSource_Builder.o tstSource_Builder_pt.o 

tstOpacity: ${tstOpacity_dep}
	${LD} ${LDFLAGS} -o $@ ${tstOpacity_dep} ${testlibs}

tstTally: ${tstTally_dep}
	${LD} ${LDFLAGS} -o $@ ${tstTally_dep} ${testlibs}

tstParticle: ${tstParticle_dep}
	${LD} ${LDFLAGS} -o $@ ${tstParticle_dep} ${testlibs}

tstTopology_Builder: ${tstTopology_Builder_dep}
	${LD} ${LDFLAGS} -o $@ ${tstTopology_Builder_dep} ${testlibs}

tstSource_Builder: ${tstSource_Builder_dep}
	${LD} ${LDFLAGS} -o $@ ${tstSource_Builder_dep} ${testlibs}

###############################################################################
#			 end of draco/src/imc/test Makefile.target
###############################################################################
