#!/bin/sh

draco_usage()
{
   echo "Usage: draco [--help | --version]"
}

draco_version()
{
   echo RTT Draco 0.0.0
   echo No Copyright!
}

draco_help()
{
   draco_usage
}

for draco_option in $*
do
   case "$draco_option" in

   --version | -version)
        draco_version
        ;;

   --help | -help)
        draco_help
        ;;
   *)
        draco_usage
	exit 1;
        ;;
   esac
done
