puts "Running tests of DS++ Assert component."

load_lib draco.exp

global ENV

puts "value of ENV is $ENV"

puts "Running tstAssert_$ENV"

set output [exec tstAssert_$ENV]

# Check the output of t1

if {[regexp "t1: passed" $output]} {
    pass t1
} else {
    fail t1
}

# Check the output of t2

if {[regexp "t2: passed" $output]} {
    pass t2
} else {
    fail t2
}

# Check the output of t3

if {[regexp "t3: passed" $output]} {
    pass t3
} else {
    fail t3
}

# Check the output of t4

if {[regexp "t4: passed" $output]} {
    pass t4
} else {
    fail t4
}

# Check the output of t5

if {[regexp "t5: passed" $output]} {
    pass t5
} else {
    fail t5
}


# All done with tests of tstAssert_$(env)
