###############################################################################
# draco/src/POOMA_MT/test Makefile.target
# Randy M. Roberts
# $Id$
###############################################################################
# @> Target makefile for POOMA_MT component tests
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

ptCCsrc := $(wildcard ${srcdir}/*_pt.cc)
ptObjs := $(notdir $(patsubst %.cc,%.o,${ptCCsrc}))

utilObjs := ${ptObjs} TestRelease.o utils.o

${test_alltarget}: ${testdeps}

%: %.o ${utilObjs}
	${LD} ${LDFLAGS} -o $@ $< ${utilObjs} ${testlibs}

###############################################################################
#			 end of draco/src/POOMA_MT/test Makefile.target
###############################################################################
