###############################################################################
# draco/src/cdi_gandolf/test Makefile.target
# Kelly Thompson
# $Id$
###############################################################################
# @> Target makefile for MESHREADERS component tests
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
                ${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
                ${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep     := libcdi_Test${libsuffix}
thistestlib     := -L. -lcdi_Test
thistestlib_dep := DummyGrayOpacity.o DummyMultigroupOpacity.o DummyEoS.o

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o 
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
# end of draco/src/meshReaders/test Makefile.target
###############################################################################
