draco-gnats.ps: draco-gnats.dvi
	dvips -o draco-gnats.ps draco-gnats.dvi

draco-gnats.dvi: draco-gnats.tex
	latex draco-gnats

clean:
	-rm draco-gnats.dvi draco-gnats.ps \
	        draco-gnats.log draco-gnats.aux 

