---
###########################
###########################
## Linter GitHub Actions ##
## github.com/github/super-linter
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
  push:
    branches-ignore:
      - 'master'
      - 'develop'

env:
  PYTHONPATH: /home/runner/work/Draco/Draco/config

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: develop
          ERROR_ON_MISSING_EXEC_BIT: true
          FILTER_REGEX_EXCLUDE: .*.cc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_ENV: true
          VALIDATE_HTML: true
          VALIDATE_JSON: true
          VALIDATE_LATEX: true
          VALIDATE_LUA: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PERL: true
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_POWERSHELL: true
          VALIDATE_RUBY: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
...
